[tool.poetry]
name = "rtpusher"
version = "1.4.0.dev4"
description = "Realtime Pusher"
authors = ["Jakob Schlyter <jakob@kirei.se>"]

[tool.poetry.scripts]
rtpusher = "rtpusher:cli"

[tool.poetry.dependencies]
python = "^3.9"
aiomqtt = "^1.2.1"
isodate = "^0.6.1"
pynmea2 = "^1.19.0"
PyYAML = "^6.0.1"
cryptojwt = "^1.8.3"

[tool.poetry.dev-dependencies]
pylama = "^8.4.1"
pytest = "^7.1.3"
pytest-black = "^0.3.12"
pytest-isort = "^3.0.0"
black = "^22.6.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
