[tool.poetry]
name = "rtpusher"
version = "1.4.0.dev3"
description = "Realtime Pusher"
authors = ["Jakob Schlyter <jakob@kirei.se>"]

[tool.poetry.scripts]
rtpusher = "rtpusher:main"

[tool.poetry.dependencies]
python = "^3.9"
asyncio-mqtt = "<0.17.0"
isodate = "^0.6.0"
pynmea2 = "^1.18.0"
PyYAML = "^5.4.1"
cryptojwt = "^1.5.2"

[tool.poetry.dev-dependencies]
pylama = "^8.4.1"
pytest = "^7.1.3"
pytest-black = "^0.3.12"
pytest-isort = "^3.0.0"
black = "^22.6.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
