[tool.poetry]
name = "rtpusher"
version = "1.4.0.dev1"
description = "Realtime Pusher"
authors = ["Jakob Schlyter <jakob@kirei.se>"]

[tool.poetry.dependencies]
python = "^3.9"
asyncio-mqtt = "^0.10.0"
isodate = "^0.6.0"
pynmea2 = "^1.18.0"
PyYAML = "^5.4.1"
cryptojwt = "^1.5.2"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.6.4"
pylama = "^7.7.1"
pytest = "^6.2.0"
pytest-black = "^0.3.12"
pytest-isort = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
rtpusher = "rtpusher:main"
